image:
  file: .gitpod.Dockerfile


tasks:
  - name: Setup LocalStack
    command: docker-compose -f LOCALSTACK/docker-compose.yml up -d 

ports:
  - name: LocalStack4566
    port: 4566
    onOpen: ignore
    visibility: public