AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: lambda local demo

Resources:
  simpleLambda: #name used in the CLI
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/simple-lambda/
      Handler: simple-lambda.handler # fileName/functionName
      MemorySize: 16
      Runtime: nodejs18.x
  complexLambda:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENVIRONMENT: dev
          EMBEDDING_CPU_THRESHOLD: 95
          EMBEDDING_MEMORY_THRESHOLD: 90
          WEBHOOK_URL: 
      FunctionName: UserAppStack_ES_Alarms_dev
      CodeUri: lambda/es-alarms/
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs16.x
      Timeout: 120
      # Layers:
      #   - arn:aws:lambda:us-east-1::layer:nodevibrant082A2997:5
      #   - arn:aws:lambda:us-east-1::layer:rssparser841E25B9:3
      #   - arn:aws:lambda:us-east-1::layer:pcksharp87135751:23
